<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-EI1MF8H" failures="1" tests="5" name="superAdmin.Login" time="40.984" errors="0" timestamp="2022-01-30T15:50:17 BDT" skipped="0">
  <testcase classname="superAdmin.Login" name="verifyElemntsOnPageTest" time="10.363"/>
  <system-out/>
  <testcase classname="superAdmin.Login" name="verifyLogin" time="9.659">
    <failure message="expected [https://dev.zntral.net/dashboard] but found [https://dev.zntral.net/session/login]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://dev.zntral.net/dashboard] but found [https://dev.zntral.net/session/login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at superAdmin.Login.verifyLogin(Login.java:122)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- verifyLogin -->
  <system-out/>
  <testcase classname="superAdmin.Login" name="loginWithoutUsername" time="5.669"/>
  <system-out/>
  <testcase classname="superAdmin.Login" name="loginWithoutPassword" time="5.749"/>
  <system-out/>
  <testcase classname="superAdmin.Login" name="invalidLoginInfo" time="9.544"/>
  <system-out/>
</testsuite> <!-- superAdmin.Login -->
